name: Docker Image CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
  

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Auth image
      run: docker build . --file /src/painty-dev-backend/Services/Authentication/Authentication.Api/Dockerfile --tag authentication-api:$(date +%s)
      
    - name: Build the Communicate image
      run: docker build . --file /src/painty-dev-backend/Services/Communicate/Cummunicate.Api/Dockerfile --tag communicate-api:$(date +%s)
